server:
  port: 8078

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: --- secret ---


greeting:
  message: result-service

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh

aws:
  region: --- secret ---
  accessKey: --- secret ---
  secretKey: --- secret ---
  sqs:
    queueUrl: --- secret ---

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: result-service

  messages:
    basename: errors
    encoding: utf-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liardev3
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6381